import { BASE_PATH_FRAGMENT, PROPERTY_ID_PATH_FRAGMENT } from '../constants';

export const RESOURCE_NAME = 'roomtype';

export const PATHNAME_TEMPLATE = `${BASE_PATH_FRAGMENT}/${RESOURCE_NAME}${PROPERTY_ID_PATH_FRAGMENT}`;
