import { WEBSITE_ID_PATH_FRAGMENT, LANGUAGE_CODE_FRAGMENT } from '../constants';

export const RESOURCE_NAME = 'subscribe';

export const PATHNAME_TEMPLATE = `${WEBSITE_ID_PATH_FRAGMENT}${LANGUAGE_CODE_FRAGMENT}/${RESOURCE_NAME}`;
