import { BASE_PATH_FRAGMENT, WEBSITE_ID_PATH_FRAGMENT } from '../constants';

export const RESOURCE_NAME = 'locations';

export const PATHNAME_TEMPLATE = `${BASE_PATH_FRAGMENT}/${RESOURCE_NAME}${WEBSITE_ID_PATH_FRAGMENT}`;
