import {
  BASE_PATH_FRAGMENT,
  WEBSITE_ID_PATH_FRAGMENT,
  LANGUAGE_CODE_PLACEHOLDER,
  PROPERTY_ID_PATH_FRAGMENT,
} from '../constants';

export const RESOURCE_NAME = 'properties';

export const PATHNAME_TEMPLATE = `${BASE_PATH_FRAGMENT}/${RESOURCE_NAME}${WEBSITE_ID_PATH_FRAGMENT}${PROPERTY_ID_PATH_FRAGMENT}/description/${LANGUAGE_CODE_PLACEHOLDER}`;
